---
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: utils
build:
  artifacts:
    - image: release
      platforms: [linux/amd64, linux/arm64]
      docker:
        dockerfile: release/Dockerfile
    - image: ks3util
      platforms: [linux/amd64, linux/arm64]
      docker:
        dockerfile: ks3util/Dockerfile
    - image: remote
      platforms: [linux/amd64, linux/arm64]
      docker:
        dockerfile: remote/Dockerfile
  local:
    useDockerCLI: true
    useBuildkit: true
    concurrency: 0
    tryImportMissing: true
