# hub.pingcap.net/bases/tidb-base:v1.7.0
# hub.pingcap.net/bases/tidb-base:v1.7
# hub.pingcap.net/bases/tidb-base:v1
ARG PINGCAP_BASE
FROM $PINGCAP_BASE
RUN dnf install --allowerasing -y curl wget && dnf clean all
