# hub.pingcap.net/bases/tidb-base:v1.5.1
# hub.pingcap.net/bases/tidb-base:v1.5
# hub.pingcap.net/bases/tidb-base:v1
FROM hub.pingcap.net/bases/pingcap-base:v1.5.0
RUN dnf install --allowerasing -y curl wget && dnf clean all
