# hub.pingcap.net/bases/tidb-base:v1.4.0
# hub.pingcap.net/bases/tidb-base:v1.4
# hub.pingcap.net/bases/tidb-base:v1
FROM hub.pingcap.net/bases/pingcap-base:v1.4.0
RUN dnf install --allowerasing -y curl && dnf clean all
