# Ref: https://skaffold.dev/docs/builders/builder-types/docker/#dockerfile-in-cluster-with-kaniko
---
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: builder-go
build:
  artifacts:
    - image: tidb
      platforms: [linux/amd64, linux/arm64]
      kaniko:
        dockerfile: tidb/Dockerfile
        cache: {}
        target: builder
    - image: tiflow
      platforms: [linux/amd64, linux/arm64]
      kaniko:
        dockerfile: tiflow/Dockerfile
        cache: {}
        target: builder
    - image: pd
      platforms: [linux/amd64, linux/arm64]
      kaniko:
        dockerfile: pd/Dockerfile
        cache: {}
        target: builder
    - image: ng-monitoring
      platforms: [linux/amd64, linux/arm64]
      kaniko:
        dockerfile: ng-monitoring/Dockerfile
        cache: {}
        target: builder
  tagPolicy:
    customTemplate:
      template: "{{ .SHA }}"
      components:
        - name: SHA
          gitCommit:
            variant: Tags
  cluster:
    concurrency: 0
    randomDockerConfigSecret: false
    randomPullSecret: false
    dockerConfig:
      secretName: hub-pingcap-net-ee
    resources:
      limits:
        cpu: "4"
        memory: 8Gi
profiles:
  - name: local-docker
    build:
      local:
        useDockerCLI: true
        useBuildkit: true
        concurrency: 0
        tryImportMissing: true
    patches:
      - { op: move, from: /build/artifacts/0/kaniko, path: /build/artifacts/0/docker }
      - { op: move, from: /build/artifacts/1/kaniko, path: /build/artifacts/1/docker }
      - { op: move, from: /build/artifacts/2/kaniko, path: /build/artifacts/2/docker }
      - { op: move, from: /build/artifacts/3/kaniko, path: /build/artifacts/3/docker }
  - name: go-1.21
    patches:
      - op: replace
        path: /build/tagPolicy/customTemplate/template
        value: "{{ .SHA }}-go1.21"
      - op: add
        path: /build/artifacts/0/kaniko/buildArgs
        value: &value-go1-21
          # renovate: datasource=docker depName=golang
          GOLANG_VERSION: 1.21.6
      - op: add
        path: /build/artifacts/1/kaniko/buildArgs
        value: *value-go1-21
      - op: add
        path: /build/artifacts/2/kaniko/buildArgs
        value: *value-go1-21
      - op: add
        path: /build/artifacts/3/kaniko/buildArgs
        value: *value-go1-21
  - name: go-1.20
    patches:
      - op: replace
        path: /build/tagPolicy/customTemplate/template
        value: "{{ .SHA }}-go1.20"
      - op: add
        path: /build/artifacts/0/kaniko/buildArgs
        value: &value-go1-20
          # renovate: datasource=docker depName=golang
          GOLANG_VERSION: 1.20.14
      - op: add
        path: /build/artifacts/1/kaniko/buildArgs
        value: *value-go1-20
      - op: add
        path: /build/artifacts/2/kaniko/buildArgs
        value: *value-go1-20
      - op: add
        path: /build/artifacts/2/kaniko/buildArgs
        value: *value-go1-20
  - name: go-1.19
    patches:
      - op: replace
        path: /build/tagPolicy/customTemplate/template
        value: "{{ .SHA }}-go1.19"
      - op: add
        path: /build/artifacts/0/kaniko/buildArgs
        value: &value-go1-19
          GOLANG_VERSION: 1.19.13
      - op: add
        path: /build/artifacts/1/kaniko/buildArgs
        value: *value-go1-19
      - op: add
        path: /build/artifacts/2/kaniko/buildArgs
        value: *value-go1-19
      - op: add
        path: /build/artifacts/3/kaniko/buildArgs
        value: *value-go1-19
  - name: go-1.18
    patches:
      - op: replace
        path: /build/tagPolicy/customTemplate/template
        value: "{{ .SHA }}-go1.18"
      - op: add
        path: /build/artifacts/0/kaniko/buildArgs
        value: &value-go1-18
          GOLANG_VERSION: 1.18.10
      - op: add
        path: /build/artifacts/1/kaniko/buildArgs
        value: *value-go1-18
      - op: add
        path: /build/artifacts/2/kaniko/buildArgs
        value: *value-go1-18
      - op: add
        path: /build/artifacts/3/kaniko/buildArgs
        value: *value-go1-18
---
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: builder-others
build:
  artifacts:
    - image: tikv
      platforms: [linux/amd64, linux/arm64]
      kaniko:
        dockerfile: tikv/Dockerfile
        cache: {}
        target: builder
    - image: tidb-dashboard
      platforms: [linux/amd64, linux/arm64]
      kaniko:
        dockerfile: tidb-dashboard/Dockerfile
        cache: {}
        target: builder
  cluster:
    concurrency: 0
    randomDockerConfigSecret: false
    randomPullSecret: false
    dockerConfig:
      secretName: hub-pingcap-net-ee
    resources:
      limits:
        cpu: "8"
        memory: 32Gi
profiles:
  - name: local-docker
    build:
      local:
        useDockerCLI: true
        useBuildkit: true
        concurrency: 0
        tryImportMissing: true
    patches:
      - { op: move, from: /build/artifacts/0/kaniko, path: /build/artifacts/0/docker }
      - { op: move, from: /build/artifacts/1/kaniko, path: /build/artifacts/1/docker }
---
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: builder-others-slow
build:
  artifacts:
    - image: tiflash
      platforms: [linux/amd64, linux/arm64]
      kaniko:
        dockerfile: tiflash/Dockerfile
        cache: {}
        target: builder
  cluster:
    concurrency: 0
    randomDockerConfigSecret: false
    randomPullSecret: false
    dockerConfig:
      secretName: hub-pingcap-net-ee
    resources:
      limits:
        cpu: "8"
        memory: 32Gi
profiles:
  - name: local-docker
    build:
      local:
        useDockerCLI: true
        useBuildkit: true
        concurrency: 0
        tryImportMissing: true
    patches:
      - { op: move, from: /build/artifacts/0/kaniko, path: /build/artifacts/0/docker }
---
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: builder-others-fips
build:
  artifacts:
    - image: tikv
      platforms: [linux/amd64, linux/arm64]
      kaniko:
        dockerfile: tikv/fips.Dockerfile
        cache: {}
        target: builder
  tagPolicy:
    customTemplate:
      template: "{{ .SHA }}-fips"
      components:
        - name: SHA
          gitCommit:
            variant: Tags
  cluster:
    concurrency: 0
    randomDockerConfigSecret: false
    randomPullSecret: false
    dockerConfig:
      secretName: hub-pingcap-net-ee
    resources:
      requests:
        cpu: "1"
        memory: 2Gi
      limits:
        cpu: "2"
        memory: 4Gi
profiles:
  - name: local-docker
    build:
      local:
        useDockerCLI: true
        useBuildkit: true
        concurrency: 0
        tryImportMissing: true
    patches:
      - { op: move, from: /build/artifacts/0/kaniko, path: /build/artifacts/0/docker }
