# yaml-language-server: $schema=https://github.com/GoogleContainerTools/skaffold/raw/refs/heads/main/docs-v2/content/en/schemas/v4beta6.json
---
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: builder-go
build:
  artifacts:
    - image: tidb
      platforms: [linux/amd64, linux/arm64]
      docker:
        dockerfile: tidb/Dockerfile
        target: builder
    - image: tiflow
      platforms: [linux/amd64, linux/arm64]
      docker:
        dockerfile: tiflow/Dockerfile
        target: builder
    - image: pd
      platforms: [linux/amd64, linux/arm64]
      docker:
        dockerfile: pd/Dockerfile
        target: builder
    - image: ng-monitoring
      platforms: [linux/amd64, linux/arm64]
      docker:
        dockerfile: ng-monitoring/Dockerfile
        target: builder
    - image: tidb-dashboard
      platforms: [linux/amd64, linux/arm64]
      docker:
        dockerfile: tidb-dashboard/Dockerfile
        target: builder
    - image: tidb-operator
      platforms: [linux/amd64, linux/arm64]
      docker:
        dockerfile: tidb-operator/Dockerfile
        target: builder
  tagPolicy:
    customTemplate:
      template: "{{ .SHA }}"
      components:
        - name: SHA
          gitCommit:
            variant: Tags
  local:
    useDockerCLI: true
    useBuildkit: true
    concurrency: 0
    tryImportMissing: true
profiles:
  - name: go-1.23
    patches:
      - op: replace
        path: /build/tagPolicy/customTemplate/template
        value: "{{ .SHA }}-go1.23"
      - op: add
        path: /build/artifacts/0/docker/buildArgs
        value: &value-go1-23
          # renovate: datasource=docker depName=golang
          GOLANG_VERSION: 1.23.3
      - op: add
        path: /build/artifacts/1/docker/buildArgs
        value: *value-go1-23
      - op: add
        path: /build/artifacts/2/docker/buildArgs
        value: *value-go1-23
      - op: add
        path: /build/artifacts/3/docker/buildArgs
        value: *value-go1-23
      - op: add
        path: /build/artifacts/4/docker/buildArgs
        value: *value-go1-23
      - op: add
        path: /build/artifacts/5/docker/buildArgs
        value: *value-go1-23
  - name: go-1.22
    patches:
      - op: replace
        path: /build/tagPolicy/customTemplate/template
        value: "{{ .SHA }}-go1.22"
      - op: add
        path: /build/artifacts/0/docker/buildArgs
        value: &value-go1-22
          # renovate: datasource=docker depName=golang
          GOLANG_VERSION: 1.22.8
      - op: add
        path: /build/artifacts/1/docker/buildArgs
        value: *value-go1-22
      - op: add
        path: /build/artifacts/2/docker/buildArgs
        value: *value-go1-22
      - op: add
        path: /build/artifacts/3/docker/buildArgs
        value: *value-go1-22
      - op: add
        path: /build/artifacts/4/docker/buildArgs
        value: *value-go1-22
      - op: add
        path: /build/artifacts/5/docker/buildArgs
        value: *value-go1-22
  - name: go-1.21
    patches:
      - op: replace
        path: /build/tagPolicy/customTemplate/template
        value: "{{ .SHA }}-go1.21"
      - op: add
        path: /build/artifacts/0/docker/buildArgs
        value: &value-go1-21
          GOLANG_VERSION: 1.21.13
      - op: add
        path: /build/artifacts/1/docker/buildArgs
        value: *value-go1-21
      - op: add
        path: /build/artifacts/2/docker/buildArgs
        value: *value-go1-21
      - op: add
        path: /build/artifacts/3/docker/buildArgs
        value: *value-go1-21
      - op: add
        path: /build/artifacts/4/docker/buildArgs
        value: *value-go1-21
      - op: add
        path: /build/artifacts/5/docker/buildArgs
        value: *value-go1-21
---
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: builder-tikv
build:
  artifacts:
    - image: tikv
      platforms: [linux/amd64, linux/arm64]
      docker:
        dockerfile: tikv/Dockerfile
        target: builder
  local:
    useDockerCLI: true
    useBuildkit: true
    concurrency: 0
    tryImportMissing: true
  tagPolicy:
    customTemplate:
      template: "{{ .SHA }}"
      components:
        - name: SHA
          gitCommit:
            variant: Tags
---
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: builder-tiflash
build:
  artifacts:
    - image: tiflash
      platforms: [linux/amd64, linux/arm64]
      docker:
        dockerfile: tiflash/Dockerfile
        target: builder
  local:
    useDockerCLI: true
    useBuildkit: true
    concurrency: 0
    tryImportMissing: true
---
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: builder-tikv-fips
build:
  artifacts:
    - image: tikv
      platforms: [linux/amd64, linux/arm64]
      docker:
        dockerfile: tikv/fips.Dockerfile
        target: builder
  tagPolicy:
    customTemplate:
      template: "{{ .SHA }}-fips"
      components:
        - name: SHA
          gitCommit:
            variant: Tags
  local:
    useDockerCLI: true
    useBuildkit: true
    concurrency: 0
    tryImportMissing: true
