---
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: builder-go
build:
  artifacts:
    - image: tidb
      platforms: [linux/amd64, linux/arm64]
      docker:
        dockerfile: tidb/centos7/Dockerfile
        target: builder
    - image: tiflow
      platforms: [linux/amd64, linux/arm64]
      docker:
        dockerfile: tiflow/centos7/Dockerfile
        target: builder
    - image: pd
      platforms: [linux/amd64, linux/arm64]
      docker:
        dockerfile: pd/centos7/Dockerfile
        target: builder
    - image: ng-monitoring
      platforms: [linux/amd64, linux/arm64]
      docker:
        dockerfile: ng-monitoring/centos7/Dockerfile
        target: builder
    - image: tidb-dashboard
      platforms: [linux/amd64, linux/arm64]
      docker:
        dockerfile: tidb-dashboard/centos7/Dockerfile
        target: builder
  tagPolicy:
    customTemplate:
      template: "{{ .SHA }}-centos7"
      components:
        - name: SHA
          gitCommit:
            variant: Tags
  local:
    useDockerCLI: true
    useBuildkit: true
    concurrency: 0
    tryImportMissing: true
profiles:
  - name: go-1.23
    patches:
      - op: replace
        path: /build/tagPolicy/customTemplate/template
        value: "{{ .SHA }}-centos7-go1.23"
      - op: add
        path: /build/artifacts/0/docker/buildArgs
        value: &value-go1-23
          # renovate: datasource=docker depName=golang
          GOLANG_VERSION: 1.23.1
      - op: add
        path: /build/artifacts/1/docker/buildArgs
        value: *value-go1-23
      - op: add
        path: /build/artifacts/2/docker/buildArgs
        value: *value-go1-23
      - op: add
        path: /build/artifacts/3/docker/buildArgs
        value: *value-go1-23
      - op: add
        path: /build/artifacts/4/docker/buildArgs
        value: *value-go1-23
  - name: go-1.22
    patches:
      - op: replace
        path: /build/tagPolicy/customTemplate/template
        value: "{{ .SHA }}-centos7-go1.22"
      - op: add
        path: /build/artifacts/0/docker/buildArgs
        value: &value-go1-22
          # renovate: datasource=docker depName=golang
          GOLANG_VERSION: 1.22.7
      - op: add
        path: /build/artifacts/1/docker/buildArgs
        value: *value-go1-22
      - op: add
        path: /build/artifacts/2/docker/buildArgs
        value: *value-go1-22
      - op: add
        path: /build/artifacts/3/docker/buildArgs
        value: *value-go1-22
      - op: add
        path: /build/artifacts/4/docker/buildArgs
        value: *value-go1-22
  - name: go-1.21
    patches:
      - op: replace
        path: /build/tagPolicy/customTemplate/template
        value: "{{ .SHA }}-centos7-go1.21"
      - op: add
        path: /build/artifacts/0/docker/buildArgs
        value: &value-go1-21
          GOLANG_VERSION: 1.21.13
      - op: add
        path: /build/artifacts/1/docker/buildArgs
        value: *value-go1-21
      - op: add
        path: /build/artifacts/2/docker/buildArgs
        value: *value-go1-21
      - op: add
        path: /build/artifacts/3/docker/buildArgs
        value: *value-go1-21
      - op: add
        path: /build/artifacts/4/docker/buildArgs
        value: *value-go1-21
  - name: go-1.20
    patches:
      - op: replace
        path: /build/tagPolicy/customTemplate/template
        value: "{{ .SHA }}-centos7-go1.20"
      - op: add
        path: /build/artifacts/0/docker/buildArgs
        value: &value-go1-20
          GOLANG_VERSION: 1.20.14
      - op: add
        path: /build/artifacts/1/docker/buildArgs
        value: *value-go1-20
      - op: add
        path: /build/artifacts/2/docker/buildArgs
        value: *value-go1-20
      - op: add
        path: /build/artifacts/3/docker/buildArgs
        value: *value-go1-20
      - op: add
        path: /build/artifacts/4/docker/buildArgs
        value: *value-go1-20
  - name: go-1.19
    patches:
      - op: replace
        path: /build/tagPolicy/customTemplate/template
        value: "{{ .SHA }}-centos7-go1.19"
      - op: add
        path: /build/artifacts/0/docker/buildArgs
        value: &value-go1-19
          GOLANG_VERSION: 1.19.13
      - op: add
        path: /build/artifacts/1/docker/buildArgs
        value: *value-go1-19
      - op: add
        path: /build/artifacts/2/docker/buildArgs
        value: *value-go1-19
      - op: add
        path: /build/artifacts/3/docker/buildArgs
        value: *value-go1-19
      - op: add
        path: /build/artifacts/4/docker/buildArgs
        value: *value-go1-19
---
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: builder-tikv
build:
  artifacts:
    - image: tikv
      platforms: [linux/amd64, linux/arm64]
      docker:
        dockerfile: tikv/centos7/Dockerfile
        target: builder
  local:
    useDockerCLI: true
    useBuildkit: true
    concurrency: 0
    tryImportMissing: true
  tagPolicy:
    customTemplate:
      template: "{{ .SHA }}-centos7"
      components:
        - name: SHA
          gitCommit:
            variant: Tags
profiles:
  - name: devtoolset8
    patches:
      - op: replace
        path: /build/tagPolicy/customTemplate/template
        value: "{{ .SHA }}-centos7-devtoolset8"
      - op: add
        path: /build/artifacts/0/kaniko/buildArgs
        value:
          DEVTOOLSET_VER: 8
  - name: devtoolset9
    patches:
      - op: replace
        path: /build/tagPolicy/customTemplate/template
        value: "{{ .SHA }}-centos7-devtoolset9"
      - op: add
        path: /build/artifacts/0/kaniko/buildArgs
        value:
          DEVTOOLSET_VER: 9
  - name: devtoolset10
    patches:
      - op: replace
        path: /build/tagPolicy/customTemplate/template
        value: "{{ .SHA }}-centos7-devtoolset10"
      - op: add
        path: /build/artifacts/0/kaniko/buildArgs
        value:
          DEVTOOLSET_VER: 10
---
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: builder-tiflash
build:
  artifacts:
    - image: tiflash
      platforms: [linux/amd64, linux/arm64]
      docker:
        dockerfile: tiflash/centos7/Dockerfile
        target: builder
  local:
    useDockerCLI: true
    useBuildkit: true
    concurrency: 0
    tryImportMissing: true
  tagPolicy:
    customTemplate:
      template: "{{ .SHA }}-centos7"
      components:
        - name: SHA
          gitCommit:
            variant: Tags
