name: "Setup Skaffold"
description: "Install Skaffold CLI on the runner"
inputs:
  version:
    description: 'Version of Skaffold to install (default: "latest")'
    required: false
    default: "latest"
runs:
  using: "composite"
  steps:
    - name: Install Skaffold
      shell: bash
      run: |
        url_prefix="https://storage.googleapis.com/skaffold/releases/${{ inputs.version }}"

        if [[ "$(uname)/$(uname -m)" == "Darwin/arm64" ]]; then
          url="${url_prefix}/skaffold-darwin-arm64"
        elif [[ "$(uname)/$(uname -m)" == "Darwin/x86_64" ]]; then
          url="${url_prefix}/skaffold-darwin-amd64"
        elif [[ "$(uname)/$(uname -m)" == "Linux/aarch64" ]]; then
          url="${url_prefix}/skaffold-linux-arm64"
        elif [[ "$(uname)/$(uname -m)" == "Linux/x86_64" ]]; then
          url="${url_prefix}/skaffold-linux-amd64"
        fi

        echo "Downloading Skaffold from $url"
        curl -Lo skaffold $url
        sudo install skaffold /usr/local/bin/
        skaffold version
