# yaml-language-server: $schema=https://github.com/GoogleContainerTools/skaffold/raw/refs/heads/main/docs-v2/content/en/schemas/v4beta6.json
---
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: builder
build:
  artifacts:
    - image: ng-monitoring
      platforms: [linux/amd64, linux/arm64]
      docker:
        dockerfile: Dockerfile
        target: builder
  tagPolicy:
    customTemplate:
      template: "{{ .GIT }}"
  local:
    useDockerCLI: true
    useBuildkit: true
    concurrency: 0
    tryImportMissing: true
profiles:
  - name: go-1.25
    patches:
      - op: replace
        path: /build/tagPolicy/customTemplate/template
        value: "{{ .GIT }}-go1.25"
      - op: add
        path: /build/artifacts/0/docker/buildArgs
        value:
          # renovate: datasource=docker depName=golang
          GOLANG_VERSION: 1.25.6
