# hub.pingcap.net/bases/tikv-base:v1.5.0
# hub.pingcap.net/bases/tikv-base:v1.5
# hub.pingcap.net/bases/tikv-base:v1
FROM hub.pingcap.net/bases/pingcap-base:v1.5.0
RUN dnf install -y tzdata
ENV TZ=/etc/localtime \
    TZDIR=/usr/share/zoneinfo
