FROM alpine:3.21.4

LABEL org.opencontainers.image.authors "wuhui.zuo@pingcap.com"
LABEL org.opencontainers.image.description "utils image for remote building"
LABEL org.opencontainers.image.source "https://github.com/PingCAP-QE/artifacts"

RUN apk add --no-cache bash openssh-client rsync
