# Ref: https://skaffold.dev/docs/builders/builder-types/docker
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: default
build:
  artifacts:
    - image: pingcap-base
      platforms: [linux/amd64, linux/arm64]
      docker:
        dockerfile: pingcap-base/Dockerfile
    - image: pd-base
      platforms: [linux/amd64, linux/arm64]
      requires:
        - image: pingcap-base
          alias: PINGCAP_BASE
      docker:
        dockerfile: pd-base/Dockerfile
    - image: ng-monitoring-base
      platforms: [linux/amd64, linux/arm64]
      requires:
        - image: pingcap-base
          alias: PINGCAP_BASE
      docker:
        dockerfile: ng-monitoring-base/Dockerfile
    - image: tidb-base
      platforms: [linux/amd64, linux/arm64]
      requires:
        - image: pingcap-base
          alias: PINGCAP_BASE
      docker:
        dockerfile: tidb-base/Dockerfile
    - image: tiflash-base
      platforms: [linux/amd64, linux/arm64]
      requires:
        - image: pingcap-base
          alias: PINGCAP_BASE
      docker:
        dockerfile: tiflash-base/Dockerfile
    - image: tikv-base
      platforms: [linux/amd64, linux/arm64]
      requires:
        - image: pingcap-base
          alias: PINGCAP_BASE
      docker:
        dockerfile: tikv-base/Dockerfile
    - image: tools-base
      platforms: [linux/amd64, linux/arm64]
      requires:
        - image: pingcap-base
          alias: PINGCAP_BASE
      docker:
        dockerfile: tools-base/Dockerfile
    - image: debugging
      platforms: [linux/amd64, linux/arm64]
      requires:
        - image: pingcap-base
          alias: PINGCAP_BASE
      docker:
        dockerfile: debugging/Dockerfile
  tagPolicy:
    customTemplate:
      template: "v1.11.0"
  local:
    useDockerCLI: true
    useBuildkit: true
    concurrency: 0
    tryImportMissing: true

---
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: fips
build:
  artifacts:
    - image: tikv-base
      platforms: [linux/amd64, linux/arm64]
      docker:
        dockerfile: tikv-base/fips.Dockerfile
  tagPolicy:
    customTemplate:
      template: "v1.10.1-fips"
  local:
    useDockerCLI: true
    useBuildkit: true
    concurrency: 0
    tryImportMissing: true
---
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: release-6-5
build:
  artifacts:
    - image: ng-monitoring-base
      platforms: [linux/amd64, linux/arm64]
      custom:
        buildCommand: ./build-old.sh ng-monitoring-base release-6.5.Dockerfile
        dependencies:
          dockerfile:
            path: ng-monitoring-base/release-6.5.Dockerfile
    - image: pd-base
      platforms: [linux/amd64, linux/arm64]
      custom:
        buildCommand: ./build-old.sh pd-base release-6.5.Dockerfile
        dependencies:
          dockerfile:
            path: pd-base/release-6.5.Dockerfile
    - image: tidb-base
      platforms: [linux/amd64, linux/arm64]
      custom:
        buildCommand: ./build-old.sh tidb-base release-6.5.Dockerfile
        dependencies:
          dockerfile:
            path: tidb-base/release-6.5.Dockerfile
    - image: tiflash-base
      platforms: [linux/amd64, linux/arm64]
      docker:
        dockerfile: tiflash-base/release-6.5.Dockerfile
        noCache: false
        pullParent: false
        squash: false
    - image: tiflow-base
      platforms: [linux/amd64, linux/arm64]
      custom:
        buildCommand: ./build-old.sh tiflow-base release-6.5.Dockerfile
        dependencies:
          dockerfile:
            path: tiflow-base/release-6.5.Dockerfile
    - image: tikv-base
      platforms: [linux/amd64, linux/arm64]
      custom:
        buildCommand: ./build-old.sh tikv-base release-6.5.Dockerfile
        dependencies:
          dockerfile:
            path: tikv-base/release-6.5.Dockerfile
    - image: tools-base
      platforms: [linux/amd64, linux/arm64]
      custom:
        buildCommand: ./build-old.sh tools-base release-6.5.Dockerfile
        dependencies:
          dockerfile:
            path: tools-base/release-6.5.Dockerfile
  tagPolicy:
    customTemplate:
      template: "v1.0.1-old"
  local:
    useDockerCLI: true
    useBuildkit: true
    concurrency: 0
    tryImportMissing: true
