# hub.pingcap.net/bases/pd-base:v1.7.0
# hub.pingcap.net/bases/pd-base:v1.7
# hub.pingcap.net/bases/pd-base:v1
FROM hub.pingcap.net/bases/pingcap-base:v1.7.0
RUN dnf install bind-utils wget jq -y && \
    dnf clean all
