# hub.pingcap.net/bases/pd-base:v1.4.0
# hub.pingcap.net/bases/pd-base:v1.4
# hub.pingcap.net/bases/pd-base:v1
FROM hub.pingcap.net/bases/pingcap-base:v1.4.0
RUN dnf install bind-utils wget -y && \
    dnf clean all
