# yaml-language-server: $schema=https://github.com/GoogleContainerTools/skaffold/raw/refs/heads/main/docs-v2/content/en/schemas/v4beta6.json
#
# build for CentOS 7 based builder images
---
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: builder
build:
  artifacts:
    - image: tikv
      platforms: [linux/amd64, linux/arm64]
      docker:
        dockerfile: centos7/Dockerfile
        target: builder
  local:
    useDockerCLI: true
    useBuildkit: true
    concurrency: 0
    tryImportMissing: true
  tagPolicy:
    customTemplate:
      template: "{{ .GIT }}-centos7{{ .TAG_SUFFIX }}"
      components:
        - name: TAG_SUFFIX
          envTemplate:
            template: "{{ if .DTS_VER }}-devtoolset{{ .DTS_VER }}{{ end }}{{ if .NON_ROOT }}-non-root{{ end }}"
profiles:
  - name: non-root-builder
    activation:
      - env: NON_ROOT=true
    patches:
      - op: replace
        path: /build/artifacts/0/docker/target
        value: non-root-builder
  - name: devtoolset8
    activation:
      - env: DTS_VER=8
    patches:
      - op: add
        path: /build/artifacts/0/docker/buildArgs
        value:
          DEVTOOLSET_VER: 8
  - name: devtoolset9
    activation:
      - env: DTS_VER=9
    patches:
      - op: add
        path: /build/artifacts/0/docker/buildArgs
        value:
          DEVTOOLSET_VER: 9
  - name: devtoolset10
    activation:
      - env: DTS_VER=10
    patches:
      - op: add
        path: /build/artifacts/0/docker/buildArgs
        value:
          DEVTOOLSET_VER: 10
