# hub.pingcap.net/bases/ng-monitoring-base:v1.7.0
# hub.pingcap.net/bases/ng-monitoring-base:v1.7
# hub.pingcap.net/bases/ng-monitoring-base:v1
ARG PINGCAP_BASE
FROM $PINGCAP_BASE
RUN dnf install perl-interpreter -y && \
    dnf clean all
