# Ref: https://skaffold.dev/docs/builders/builder-types/docker
---
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: ci
build:
  artifacts:
    - image: base
      platforms: [linux/amd64, linux/arm64]
      docker:
        dockerfile: base/Dockerfile
    - image: jenkins
      platforms: [linux/amd64, linux/arm64]
      docker:
        dockerfile: jenkins/Dockerfile
      requires:
        - image: base
          alias: BASE_IMG
  tagPolicy:
    customTemplate:
      template: "{{ .SHA }}"
      components:
        - name: SHA
          gitCommit:
            variant: Tags
  local:
    useDockerCLI: true
    useBuildkit: true
    concurrency: 0
    tryImportMissing: true
profiles:
  - name: go-1.23
    patches:
      - op: replace
        path: /build/tagPolicy/customTemplate/template
        value: "{{ .SHA }}-go1.23"
      - op: add
        path: /build/artifacts/0/docker/buildArgs
        value: &value-go1-23
          # renovate: datasource=docker depName=golang
          GOLANG_VERSION: 1.23.4
      - op: add
        path: /build/artifacts/0/docker/buildArgs
        value: *value-go1-23
  - name: go-1.22
    patches:
      - op: replace
        path: /build/tagPolicy/customTemplate/template
        value: "{{ .SHA }}-go1.22"
      - op: add
        path: /build/artifacts/0/docker/buildArgs
        value: &value-go1-22
          # renovate: datasource=docker depName=golang
          GOLANG_VERSION: 1.22.10
      - op: add
        path: /build/artifacts/1/docker/buildArgs
        value: *value-go1-22
  - name: go-1.21
    patches:
      - op: replace
        path: /build/tagPolicy/customTemplate/template
        value: "{{ .SHA }}-go1.21"
      - op: add
        path: /build/artifacts/0/docker/buildArgs
        value: &value-go1-21
          GOLANG_VERSION: 1.21.13 # EOL
      - op: add
        path: /build/artifacts/1/docker/buildArgs
        value: *value-go1-21
---
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: ci-jenkins-tikv
build:
  artifacts:
    - image: tikv
      platforms: [linux/amd64, linux/arm64]
      docker:
        dockerfile: jenkins/tikv/Dockerfile
  tagPolicy:
    customTemplate:
      template: "{{ .SHA }}"
      components:
        - name: SHA
          gitCommit:
            variant: Tags
  local:
    useDockerCLI: true
    useBuildkit: true
    concurrency: 0
    tryImportMissing: true
---
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: ci-jenkins-tiflash
build:
  artifacts:
    - image: tiflash
      platforms: [linux/amd64, linux/arm64]
      docker:
        dockerfile: jenkins/tiflash/Dockerfile
  tagPolicy:
    customTemplate:
      template: "{{ .SHA }}"
      components:
        - name: SHA
          gitCommit:
            variant: Tags
  local:
    useDockerCLI: true
    useBuildkit: true
    concurrency: 0
    tryImportMissing: true
