# hub.pingcap.net/bases/tools-base:v1.3.0
# hub.pingcap.net/bases/tools-base:v1.3
# hub.pingcap.net/bases/tools-base:v1
FROM hub.pingcap.net/bases/pingcap-base:v1.3.0
RUN dnf install -y bind-utils wget nc && dnf clean all
