# hub.pingcap.net/bases/tools-base:v1.7.0
# hub.pingcap.net/bases/tools-base:v1.7
# hub.pingcap.net/bases/tools-base:v1
ARG PINGCAP_BASE
FROM $PINGCAP_BASE
RUN dnf install -y bind-utils wget nc && dnf clean all
