---
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: builder
build:
  artifacts:
    - image: tiflash
      platforms: [linux/amd64, linux/arm64]
      docker:
        dockerfile: centos7/Dockerfile
        target: builder
  local:
    useDockerCLI: true
    useBuildkit: true
    concurrency: 0
    tryImportMissing: true
  tagPolicy:
    customTemplate:
      template: "{{ .GIT }}-centos7{{ .TAG_SUFFIX }}"
      components:
        - name: TAG_SUFFIX
          envTemplate:
            template: "-go{{ .GO_VER_XY }}{{ if .NON_ROOT }}-non-root{{ end }}"
profiles:
  - name: non-root-builder
    activation:
      - env: NON_ROOT=true
    patches:
      - op: replace
        path: /build/artifacts/0/docker/target
        value: non-root-builder
