# yaml-language-server: $schema=https://github.com/GoogleContainerTools/skaffold/raw/refs/heads/main/docs-v2/content/en/schemas/v4beta6.json
---
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: builder
build:
  artifacts:
    - image: tiflash
      platforms: [linux/amd64, linux/arm64]
      docker:
        dockerfile: Dockerfile
        target: non-root-builder
  tagPolicy:
    customTemplate:
      template: "{{ .GIT }}-non-root"
  local:
    useDockerCLI: true
    useBuildkit: true
    concurrency: 0
    tryImportMissing: true
