---
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: builder
build:
  artifacts:
    - image: tiflash
      platforms: [linux/amd64, linux/arm64]
      docker:
        dockerfile: centos7/Dockerfile
        target: non-root-builder
  tagPolicy:
    customTemplate:
      template: "{{ .GIT }}-centos7-non-root"
  local:
    useDockerCLI: true
    useBuildkit: true
    concurrency: 0
    tryImportMissing: true