# Ref: https://skaffold.dev/docs/builders/builder-types/docker/
# --- Go v1.21.0
apiVersion: skaffold/v4beta6
kind: Config
build:
  platforms: [linux/amd64, linux/arm64]
  local: {}
  artifacts:
    - image: hub.pingcap.net/ee/ci/base
      docker:
        dockerfile: base/Dockerfile
        cacheFrom:
          - hub.pingcap.net/ee/ci/base
        buildArgs:
          GOLANG_VERSION: 1.21.0
    - image: hub.pingcap.net/ee/ci/release-build-base
      docker:
        dockerfile: release-build-base/Dockerfile
        cacheFrom:
          - dockerfiles/ci-runtimes/release-build-base
        buildArgs:
          GOLANG_VERSION: 1.21.0
  tagPolicy:
    customTemplate:
      template: "v{{ .DATE }}-{{ .SHA }}-go1.21.0"
      components:
        - name: DATE
          dateTime:
            format: "20060102"
            timezone: "UTC"
        - name: SHA
          gitCommit:
            variant: AbbrevCommitSha
---
# --- Go v1.20.x
apiVersion: skaffold/v4beta6
kind: Config
build:
  platforms: [linux/amd64, linux/arm64]
  local: {}
  artifacts:
    - image: hub.pingcap.net/ee/ci/base
      docker:
        dockerfile: base/Dockerfile
        cacheFrom:
          - hub.pingcap.net/ee/ci/base
        buildArgs:
          GOLANG_VERSION: 1.20.7
    - image: hub.pingcap.net/ee/ci/release-build-base
      docker:
        dockerfile: release-build-base/Dockerfile
        cacheFrom:
          - dockerfiles/ci-runtimes/release-build-base
        buildArgs:
          GOLANG_VERSION: 1.20.7
  tagPolicy:
    customTemplate:
      template: "v{{ .DATE }}-{{ .SHA }}-go1.20.7"
      components:
        - name: DATE
          dateTime:
            format: "20060102"
            timezone: "UTC"
        - name: SHA
          gitCommit:
            variant: AbbrevCommitSha
---
# --- Go v1.19.x
apiVersion: skaffold/v4beta6
kind: Config
build:
  platforms: [linux/amd64, linux/arm64]
  local: {}
  artifacts:
    - image: hub.pingcap.net/ee/ci/base
      docker:
        dockerfile: base/Dockerfile
        cacheFrom:
          - hub.pingcap.net/ee/ci/base
        buildArgs:
          GOLANG_VERSION: 1.19.12
    - image: hub.pingcap.net/ee/ci/release-build-base
      docker:
        dockerfile: release-build-base/Dockerfile
        cacheFrom:
          - dockerfiles/ci-runtimes/release-build-base
        buildArgs:
          GOLANG_VERSION: 1.19.12
  tagPolicy:
    customTemplate:
      template: "v{{ .DATE }}-{{ .SHA }}-go1.19.12"
      components:
        - name: DATE
          dateTime:
            format: "20060102"
            timezone: "UTC"
        - name: SHA
          gitCommit:
            variant: AbbrevCommitSha
---
# --- tikv and tiflash
apiVersion: skaffold/v4beta6
kind: Config
build:
  platforms: [linux/amd64, linux/arm64]
  local: {}
  artifacts:
    - image: hub.pingcap.net/ee/ci/release-build-base-tikv
      docker:
        dockerfile: release-build-base/tikv/Dockerfile
        cacheFrom:
          - hub.pingcap.net/ee/ci/release-build-base-tikv
    - image: hub.pingcap.net/ee/ci/release-build-base-tiflash
      docker:
        dockerfile: release-build-base/tiflash/Dockerfile
        cacheFrom:
          - hub.pingcap.net/ee/ci/release-build-base-tiflash
  tagPolicy:
    customTemplate:
      template: "v{{ .DATE }}-{{ .SHA }}"
      components:
        - name: DATE
          dateTime:
            format: "20060102"
            timezone: "UTC"
        - name: SHA
          gitCommit:
            variant: AbbrevCommitSha
