# hub.pingcap.net/bases/tiflash-base:v1.6.0
# hub.pingcap.net/bases/tiflash-base:v1.6
# hub.pingcap.net/bases/tiflash-base:v1
FROM hub.pingcap.net/bases/pingcap-base:v1.6.0
RUN dnf install --allowerasing -y wget && dnf clean all
