# hub.pingcap.net/bases/tiflash-base:v1.5.0
# hub.pingcap.net/bases/tiflash-base:v1.5
# hub.pingcap.net/bases/tiflash-base:v1
FROM hub.pingcap.net/bases/pingcap-base:v1.5.0
RUN dnf install --allowerasing -y wget && dnf clean all
