name: Skaffold
on:
  push:
    branches:
      - main
    paths:
      - dockerfiles/bases/**/Dockerfile
      - dockerfiles/ci/**/Dockerfile
      - .github/workflows/ci.yml
  pull_request:
    branches:
      - main
    paths:
      - dockerfiles/bases/**/Dockerfile
      - dockerfiles/ci/**/Dockerfile
      - .github/workflows/ci.yml

jobs:
  build:
    name: Skaffold Build
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache layers
        uses: actions/cache@v3
        with:
          path: "${{ github.workspace }}/.skaffold/cache"
          key: skaffold-${{ hashFiles('**/cache') }}
          restore-keys: |
            skaffold-

      - name: Build CI base images
        uses: hiberbee/github-action-skaffold@latest
        with:
          skaffold-version: 2.8.0
          command: build
          working-directory: dockerfiles/ci
          image: base
          # internal repository: hub.pingcap.net/ee/ci
          repository: ghcr.io/pingcap-qe/ci
          profile: local-docker
      - name: Build product base images
        uses: hiberbee/github-action-skaffold@latest
        if: false
        with:
          skaffold-version: 2.8.0
          command: build
          working-directory: dockerfiles/bases
          # internal repository: hub.pingcap.net/bases
          # dockerhub: pingcap/
          repository: ghcr.io/pingcap-qe/bases
          profile: local-docker
