name: Pull test for packages cfg
on:
  pull_request:
    branches:
      - main
    paths:
      - "packages/**"

jobs:
  test-packages-cfg:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Install tools
        run: |
          # install gomplate
          git clone https://github.com/hairyhenderson/gomplate && \
            pushd gomplate && \
            GOBIN=/usr/local/bin go install ./cmd/gomplate && 
            popd && 
            rm -rf gomplate && \
            gomplate --version

          # install shelldoc to check the README.md
          git clone https://github.com/endocode/shelldoc && \
            pushd shelldoc && \
            GOBIN=/usr/local/bin go install ./cmd/shelldoc && 
            popd && 
            rm -rf shelldoc && \

          # we need yq and jq.
          yq --version
          jq --version

      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Verify the README.md
      #   run: |
      #     shelldoc run --shell `which bash` packages/README.md
  
      - name: Test => Get builder
        run: |
          for cm in tidb tiflow tiflash tikv pd; do
            for os in linux darwin; do
              for ac in amd64 arm64; do
                for version in v7.5.0 v7.1.0 v6.5.0 v6.1.0; do
                  for profile in release; do
                    ./packages/scripts/get-package-builder-with-config.sh $cm $os $ac $version $profile
                  done
                done
              done
            done
          done

      - name: Test => gen package artifacts script
        run: |
          for cm in tidb tiflow tiflash tikv pd; do
            for os in linux darwin; do
              for ac in amd64 arm64; do
                for version in v7.5.0 v7.1.0 v6.5.0 v6.1.0; do
                  for profile in release; do
                    ./packages/scripts/gen-package-artifacts-with-config.sh $cm $os $ac $version $profile branch-xxx 123456789abcdef
                  done
                done
              done
            done
          done

      - name: Test => gen package images script
        run: |
          for cm in tidb tiflow tiflash tikv pd; do
            for ac in amd64 arm64; do
              for version in v7.5.0 v7.1.0 v6.5.0 v6.1.0; do
                for profile in release; do
                  ./packages/scripts/gen-package-images-with-config.sh $cm linux $ac $version $profile branch-xxx 123456789abcdef
                done
              done
            done
          done
