name: Build multi stage images
on:
  issue_comment:
    types: [created]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  just-build:
    # check if the comments come from pull request, exclude those from issue.
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/just msb-') }}
    name: test building with multi stages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Checkout Pull Request
        run: gh pr checkout ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up just tool
        uses: extractions/setup-just@v2
        with:
          github-token: ${{ secrets.MY_GITHUB_TOKEN }}
          just-version: 1.34.0 # optional semver specification, otherwise latest

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Testing for tidb
        if: contains(github.event.issue.body, 'msb-tidb')
        run: just msb-tidb

      - name: Testing for pd
        if: contains(github.event.issue.body, 'msb-pd')
        run: just msb-pd

      - name: Testing for CDC of tiflow
        if: contains(github.event.issue.body, 'msb-cdc')
        run: just msb-cdc

      - name: Testing for DM of tiflow
        if: contains(github.event.issue.body, 'msb-dm')
        run: just msb-dm

      - name: Testing for TiDB Dashboard
        if: contains(github.event.issue.body, 'msb-tidb-dashboard')
        run: just msb-tidb-dashboard

      - name: Testing for TiDB Operator
        if: contains(github.event.issue.body, 'msb-tidb-operator')
        run: just msb-tidb-operator

      - name: Testing for ng-monitoring
        if: contains(github.event.issue.body, 'msb-ng-monitoring')
        run: just msb-ng-monitoring

      - name: Testing for tiflash # slow
        if: contains(github.event.issue.body, 'msb-tiflash')
        run: just msb-tiflash

      - name: Testing for tikv # slow
        if: contains(github.event.issue.body, 'msb-tikv')
        run: just msb-tikv
