name: Build multi stage images
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  just-build:
    name: test building with multi stages
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up just tool
        uses: extractions/setup-just@v2
        with:
          github-token: ${{ secrets.MY_GITHUB_TOKEN }}
          just-version: 1.34.0  # optional semver specification, otherwise latest

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - { name: Testing for tidb, run: just msb-tidb }
      - { name: Testing for pd, run: just msb-pd }
      - { name: Testing for CDC of tiflow, run: just msb-cdc }
      - { name: Testing for DM of tiflow, run: just msb-dm }
      - { name: Testing for ng-monitoring, run: just msb-ng-monitoring }
      - { name: Testing for tidb-dashboard, run: just msb-tidb-dashboard }
      - { name: Testing for tidb-operator, run: just msb-tidb-operator }
      # - { name: Testing for tiflash, run: just msb-tiflash } # slow
      # - { name: Testing for tikv, run: just msb-tikv } # slow
