name: Pull test for packages cfg
on:
  pull_request:
    branches:
      - main
    paths:
      - "packages/**"

jobs:
  test-packages-cfg:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Install tools
        run: |
          # install gomplate
          git clone https://github.com/hairyhenderson/gomplate && \
            pushd gomplate && \
            GOBIN=/usr/local/bin go install ./cmd/gomplate &&
            popd &&
            rm -rf gomplate && \
            gomplate --version

          # install shelldoc to check the README.md
          git clone https://github.com/endocode/shelldoc && \
            pushd shelldoc && \
            GOBIN=/usr/local/bin go install ./cmd/shelldoc &&
            popd &&
            rm -rf shelldoc && \

          # we need yq and jq.
          yq --version
          jq --version

      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Verify the README.md
      #   run: |
      #     shelldoc run --shell `which bash` packages/README.md

      - name: Test
        run: |
          chmod +x .github/scripts/ci.sh
          ./.github/scripts/ci.sh
