name: Build multi stage images
on:
  issue_comment:
    types: [created, edited, deleted]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  just-build:
    # check if the comments come from pull request, exclude those from issue.
    if: ${{ github.event.issue.pull_request }}

    name: test building with multi stages
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Checkout Pull Request
        run: hub pr checkout ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up just tool
        uses: extractions/setup-just@v2
        with:
          github-token: ${{ secrets.MY_GITHUB_TOKEN }}
          just-version: 1.34.0 # optional semver specification, otherwise latest

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Testing for tidb
        run: just msb-tidb
        if: contains('msb-tidb', github.event.issue.body)
      - name: Testing for pd
        run: just msb-pd
        if: contains('msb-pd', github.event.issue.body)
      - name: Testing for CDC of tiflow
        run: just msb-cdc
        if: contains('msb-cdc', github.event.issue.body)
      - name: Testing for DM of tiflow
        run: just msb-dm
        if: contains('msb-dm', github.event.issue.body)
      - name: Testing for TiDB Dashboard
        run: just msb-tidb-dashboard
        if: contains('msb-tidb-dashboard', github.event.issue.body)
      - name: Testing for TiDB Operator
        run: just msb-tidb-operator
        if: contains('msb-tidb-operator', github.event.issue.body)
      - name: Testing for ng-monitoring
        run: just msb-ng-monitoring
        if: contains('msb-ng-monitoring', github.event.issue.body)
      - name: Testing for tiflash # slow
        run: just msb-tiflash
        if: contains('msb-tiflash', github.event.issue.body) 
      - name: Testing for tikv # slow
        run: just msb-tikv
        if: contains('msb-tikv', github.event.issue.body)
