name: Pull test for CI base images
on:
  pull_request:
    branches:
      - main
    paths:
      - "dockerfiles/ci/base/**/Dockerfile"
      - "dockerfiles/ci/base/**/*.Dockerfile"
      - "dockerfiles/ci/skaffold.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  skaffold:
    name: build images with skaffold
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        go-profile: [go-1.21, go-1.20, go-1.19]
        builder-profile: [local-docker]
        platform: [linux/amd64, linux/arm64]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/v2.8.0/skaffold-linux-amd64 && \
          sudo install skaffold /usr/local/bin/

      - name: Cache layers
        uses: actions/cache@v3
        with:
          path: "~/.skaffold/cache"
          key: skaffold/${{ matrix.platform }}/ci-base-${{ matrix.go-profile }}-${{ github.sha }}
          restore-keys: |
            skaffold/${{ matrix.platform }}/ci-base-${{ matrix.go-profile }}-${{ github.sha }}
            skaffold/${{ matrix.platform }}/ci-base-${{ matrix.go-profile }}-
            skaffold/${{ matrix.platform }}/ci-base-

      - name: Build images
        working-directory: dockerfiles/ci
        run: |
          skaffold build \
            --cache-artifacts \
            --push=false \
            --platform ${{ matrix.platform }} \
            --module base \
            --profile ${{ matrix.go-profile }},${{ matrix.builder-profile }} \
            --default-repo ghcr.io/pingcap-qe/ci
