name: Pull test for building product base images
on:
  pull_request:
    branches:
      - main
    paths:
      - "dockerfiles/bases/**/Dockerfile"
      - "dockerfiles/bases/**/*.Dockerfile"
      - "dockerfiles/bases/skaffold.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  skaffold:
    name: build images with skaffold
    runs-on: ${{ matrix.runner }}

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        module: [default, fips, release-6-5]
        include:
          - platform: linux/amd64
            runner: ubuntu-24.04
          - platform: linux/arm64
            runner: ubuntu-24.04-arm

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"
          fetch-tags: "true"

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/v2.13.2/skaffold-linux-amd64 && \
          sudo install skaffold /usr/local/bin/

      - name: Setup manifest-tool
        run: |
          curl -L https://github.com/estesp/manifest-tool/releases/download/v2.1.7/binaries-manifest-tool-2.1.7.tar.gz | tar -zxvf - manifest-tool-linux-amd64
          sudo install manifest-tool-linux-amd64 /usr/local/bin/manifest-tool

      - name: Cache layers
        uses: actions/cache@v4
        with:
          path: "~/.skaffold/cache"
          key: skaffold/${{ matrix.platform }}/prod-bases-${{ github.sha }}
          restore-keys: |
            skaffold/${{ matrix.platform }}/prod-bases-

      - name: Build images
        working-directory: dockerfiles/bases
        run: |
          skaffold build \
            --build-concurrency 1 \
            --cache-artifacts \
            --default-repo ghcr.io/pingcap-qe/bases \
            --module ${{ matrix.module }} \
            --platform ${{ matrix.platform }} \
            --push=false
