name: Verify delivery config
on:
  pull_request:
    branches:
      - main
    paths:
      - schemas/delivery-schema.json
      - packages/delivery.yaml

permissions:
  contents: read

jobs:
  test-packages-cfg:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - name: Verify the json schema
        run: |
          jq . schemas/delivery-schema.json > /dev/null
      - name: Verify the delivery yaml file
        run: |
          yq . packages/delivery.yaml > /dev/null
      - name: Validate YAML against JSON schema
        uses: thiagodnf/yaml-schema-checker@3c4a632d4124b6c00e38b492b2eb35dea715e1ae
        with:
          jsonSchemaFile: schemas/delivery-schema.json
          yamlFiles: packages/delivery.yaml
