name: Pull test for packages cfg
on:
  pull_request:
    branches:
      - main
    paths:
      - "packages/**"

jobs:
  test-packages-cfg:
    runs-on: ubuntu-24.04
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
      - name: Install tools
        run: |
          # install gomplate
          GOBIN=/usr/local/bin go install github.com/hairyhenderson/gomplate/v4/cmd/gomplate@v4.3.0
          gomplate --version

          # install crane
          GOBIN=/usr/local/bin go install github.com/google/go-containerregistry/cmd/crane@v0.20.2
          crane version

          # install shelldoc to check the README.md
          git clone https://github.com/endocode/shelldoc && \
            pushd shelldoc && \
            GOBIN=/usr/local/bin go install ./cmd/shelldoc &&
            popd &&
            rm -rf shelldoc && \

          # we need yq and jq.
          yq --version
          jq --version

      - name: Checkout code
        uses: actions/checkout@v5

      # - name: Verify the README.md
      #   run: |
      #     shelldoc run --shell `which bash` packages/README.md

      - name: Test
        run: |
          chmod +x .github/scripts/ci.sh
          ./.github/scripts/ci.sh
