name: Skaffold - release
on:
  push:
    branches:
      - main
    paths:
      - dockerfiles/**/Dockerfile
      - .github/workflows/ci.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-product-bases:
    name: Skaffold release product base images
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        builder-profile: [local-docker]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            bases:
              - 'dockerfiles/bases/**'

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/v2.8.0/skaffold-linux-amd64 && \
          sudo install skaffold /usr/local/bin/

      - name: Cache layers
        uses: actions/cache@v3
        with:
          path: "~/.skaffold/cache"
          key: skaffold-${{ hashFiles('**/cache') }}
          restore-keys: |
            skaffold-

      - name: Build images
        if: steps.changes.outputs.bases == 'true'
        working-directory: dockerfiles/bases
        run: |
          skaffold build \
            --profile ${{ matrix.builder-profile }} \
            --default-repo ghcr.io/pingcap-qe/bases

  build-ci-bases:
    name: Skaffold release CI base images
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        module: [base, release-build-base]
        go-profile: [go-1.21, go-1.20, go-1.19]
        builder-profile: [local-docker]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            ${{ matrix.module }}:
              - 'dockerfiles/ci/${{ matrix.module }}**'

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/v2.8.0/skaffold-linux-amd64 && \
          sudo install skaffold /usr/local/bin/

      - name: Cache layers
        uses: actions/cache@v3
        with:
          path: "~/.skaffold/cache"
          key: skaffold-${{ hashFiles('**/cache') }}
          restore-keys: |
            skaffold-

      - name: Build images
        if: steps.changes.outputs.${{ matrix.module }} == 'true'
        working-directory: dockerfiles/ci
        run: |
          skaffold build \
            --module ${{ matrix.module }} \
            --profile ${{ matrix.go-profile }},${{ matrix.builder-profile }} \
            --default-repo ghcr.io/pingcap-qe/ci

  build-ci-utils:
    name: Skaffold release CI util images
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        module: [release-utils]
        builder-profile: [local-docker]
        platform: [linux/amd64, linux/arm64]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            ${{ matrix.module }}:
              - 'dockerfiles/ci/${{ matrix.module }}/**'

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/v2.8.0/skaffold-linux-amd64 && \
          sudo install skaffold /usr/local/bin/

      - name: Cache layers
        uses: actions/cache@v3
        with:
          path: "~/.skaffold/cache"
          key: skaffold-${{ hashFiles('**/cache') }}
          restore-keys: |
            skaffold-

      - name: Build images
        if: steps.changes.outputs.${{ matrix.module }} == 'true'
        working-directory: dockerfiles/ci
        run: |
          skaffold build \
            --module ${{ matrix.module }} \
            --profile ${{ matrix.builder-profile }} \
            --default-repo ghcr.io/pingcap-qe/ci
