name: Skaffold
on:
  push:
    branches:
      - main
    paths:
      - dockerfiles/**/Dockerfile
      - .github/workflows/ci.yml

jobs:
  build:
    name: Skaffold Build
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        go-profile: [go-1.21, go-1.20, go-1.19]
        builder-profile: [local-docker]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            bases:
              - 'dockerfiles/bases/**'
            ci:
              - 'dockerfiles/ci/**'

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/v2.8.0/skaffold-linux-amd64 && \
          sudo install skaffold /usr/local/bin/

      - name: Cache layers
        uses: actions/cache@v3
        with:
          path: "${{ github.workspace }}/.skaffold/cache"
          key: skaffold-${{ hashFiles('**/cache') }}
          restore-keys: |
            skaffold-

      - name: Build CI base images
        if: steps.changes.outputs.ci == 'true'
        working-directory: dockerfiles/ci
        run: |
          skaffold build \
            --profile ${{ matrix.go-profile }},${{ matrix.builder-profile }} \
            --default-repo ghcr.io/pingcap-qe/ci

      - name: Build product base images
        if: steps.changes.outputs.bases == 'true'
        working-directory: dockerfiles/bases
        run: |
          skaffold build \
            --profile ${{ matrix.go-profile }},${{ matrix.builder-profile }} \
            --default-repo ghcr.io/pingcap-qe/bases
