name: Publish product base images
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "dockerfiles/bases/**/Dockerfile"
      - "dockerfiles/bases/**/*.Dockerfile"
      - "dockerfiles/bases/skaffold.yaml"

jobs:
  skaffold:
    name: publish images with skaffold
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        module: [default, fips, release-6-5]
        builder-profile: [local-docker]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          fetch-tags: 'true'

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/v2.8.0/skaffold-linux-amd64 && \
          sudo install skaffold /usr/local/bin/

      - name: Cache layers
        uses: actions/cache@v3
        with:
          path: "~/.skaffold/cache"
          key: skaffold/prod-bases-${{ github.sha }}
          restore-keys: |
            skaffold/prod-bases-

      - name: Publish images
        working-directory: dockerfiles/bases
        run: |
          skaffold build \
            --build-concurrency 1 \
            --cache-artifacts \
            --default-repo ghcr.io/pingcap-qe/bases \
            --module ${{ matrix.module }} \
            --profile ${{ matrix.builder-profile }}
