name: Publish CI base images
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "dockerfiles/ci/base/**/Dockerfile"
      - "dockerfiles/ci/base/**/*.Dockerfile"
      - "dockerfiles/ci/skaffold.yaml"

jobs:
  skaffold:
    name: publish images with skaffold
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        module: [base]
        builder-profile: [local-docker]
        go-profile: [go-1.21, go-1.20, go-1.19]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          fetch-tags: 'true'

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/v2.8.0/skaffold-linux-amd64 && \
          sudo install skaffold /usr/local/bin/

      - name: Cache layers
        uses: actions/cache@v3
        with:
          path: "~/.skaffold/cache"
          key: skaffold/ci/${{ matrix.module }}/${{ matrix.go-profile }}-${{ github.sha }}
          restore-keys: |
            skaffold/ci/${{ matrix.module }}/${{ matrix.go-profile }}-
            skaffold/ci/${{ matrix.module }}/
            skaffold/ci/

      - name: Publish images
        working-directory: dockerfiles/ci
        run: |
          skaffold build \
            --build-concurrency 1 \
            --cache-artifacts \
            --default-repo ghcr.io/pingcap-qe/ci \
            --module ${{ matrix.module }} \
            --profile ${{ matrix.go-profile }},${{ matrix.builder-profile }}
