name: Publish CI base images
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "dockerfiles/ci/base/**/Dockerfile"
      - "dockerfiles/ci/base/**/*.Dockerfile"
      - "dockerfiles/ci/jenkins/**/Dockerfile"
      - "dockerfiles/ci/jenkins/**/*.Dockerfile"
      - "dockerfiles/ci/tici/**/Dockerfile"
      - "dockerfiles/ci/skaffold.yaml"

jobs:
  detect-changes:
    name: Detect file changes
    runs-on: ubuntu-24.04
    # 只有在 push 事件时才检测变更，workflow_dispatch 时跳过检测（构建所有镜像）
    if: github.event_name == 'push'
    outputs:
      base-jenkins: ${{ steps.filter.outputs.base-jenkins }}
      jenkins-special: ${{ steps.filter.outputs.jenkins-special }}
      tici: ${{ steps.filter.outputs.tici }}
      skaffold: ${{ steps.filter.outputs.skaffold }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            base-jenkins:
              - 'dockerfiles/ci/base/**/Dockerfile'
              - 'dockerfiles/ci/base/**/*.Dockerfile'
              - 'dockerfiles/ci/jenkins/Dockerfile'
            jenkins-special:
              - 'dockerfiles/ci/jenkins/tikv/**'
              - 'dockerfiles/ci/jenkins/tiflash/**'
            tici:
              - 'dockerfiles/ci/tici/**'
            skaffold:
              - 'dockerfiles/ci/skaffold.yaml'
  skaffold-go:
    name: publish images with skaffold
    runs-on: ubuntu-24.04
    needs: [detect-changes]
    if: |
      always() && 
      (github.event_name == 'workflow_dispatch' || 
       needs.detect-changes.outputs.base-jenkins == 'true' || 
       needs.detect-changes.outputs.skaffold == 'true')

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        module: [ci]
        go-profile: [go-1.24, go-1.23, go-1.22]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"
          fetch-tags: "true"

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup skaffold
        uses: heypigeonhq/setup-skaffold@v1.1.0
        with:
          version: 2.16.0

      - name: Cache layers
        uses: actions/cache@v4
        with:
          path: "~/.skaffold/cache"
          key: skaffold/ci/${{ matrix.module }}/${{ matrix.go-profile }}-${{ github.sha }}
          restore-keys: |
            skaffold/ci/${{ matrix.module }}/${{ matrix.go-profile }}-
            skaffold/ci/${{ matrix.module }}/
            skaffold/ci/

      - name: Publish images
        working-directory: dockerfiles/ci
        run: |
          skaffold build \
            --build-concurrency 1 \
            --cache-artifacts \
            --default-repo ghcr.io/pingcap-qe/ci \
            --module ${{ matrix.module }} \
            --profile ${{ matrix.go-profile }}

  skaffold-jenkins-nogo:
    name: publish images with skaffold
    runs-on: ubuntu-24.04
    needs: [detect-changes]
    if: |
      always() && 
      (github.event_name == 'workflow_dispatch' || 
       needs.detect-changes.outputs.jenkins-special == 'true' || 
       needs.detect-changes.outputs.skaffold == 'true')

    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        module: [ci-jenkins-tiflash, ci-jenkins-tikv]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"
          fetch-tags: "true"

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup skaffold
        uses: heypigeonhq/setup-skaffold@v1.1.0
        with:
          version: 2.16.0

      - name: Publish images
        working-directory: dockerfiles/ci
        run: |
          skaffold build \
            --build-concurrency 1 \
            --cache-artifacts \
            --default-repo ghcr.io/pingcap-qe/ci/jenkins \
            --module ${{ matrix.module }}

  skaffold-common:
    name: publish images with skaffold
    runs-on: ubuntu-24.04
    needs: [detect-changes]
    if: |
      always() && 
      (github.event_name == 'workflow_dispatch' || 
       needs.detect-changes.outputs.tici == 'true' || 
       needs.detect-changes.outputs.skaffold == 'true')

    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        module: [ci-tici]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"
          fetch-tags: "true"

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup skaffold
        uses: heypigeonhq/setup-skaffold@v1.1.0
        with:
          version: 2.15.0

      - name: Publish images
        working-directory: dockerfiles/ci
        run: |
          skaffold build \
            --build-concurrency 1 \
            --cache-artifacts \
            --default-repo ghcr.io/pingcap-qe/ci \
            --module ${{ matrix.module }}
